trigger:
  branches:
    include:
      - main
      - feature/*

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build the API'
  jobs:
  - job: Build
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'
        feedsToUse: select

    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--no-restore --configuration $(buildConfiguration)'

    # Requires JUnitXml.TestLogger NuGet package in the test project
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: 'tests/**/*.csproj'
        arguments: '--no-build --configuration $(buildConfiguration) --logger "junit;LogFilePath=$(Agent.TempDirectory)/TestResults/results.xml"'
        publishTestResults: false

    - task: PublishTestResults@2
      displayName: 'Publish test results'
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '$(Agent.TempDirectory)/TestResults/results.xml'

    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - $(buildConfiguration)'
      inputs:
        command: publish
        publishWebProjects: false
        projects: 'src/**/*.csproj'
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
