trigger:
  branches:
    include:
      - main
      - feature/*

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: UseDotNet@2
      displayName: Use .NET 8 SDK
      inputs:
        version: '8.x'

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'
        feedsToUse: select

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--no-restore --configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: 'tests/**/*.csproj'
        arguments: '--no-build --configuration $(buildConfiguration) --logger "junit;LogFilePath=$(Agent.TempDirectory)/TestResults/results.xml"'
        publishTestResults: false

    - task: PublishTestResults@2
      displayName: Publish test results
      inputs:
        testResultsFormat: JUnit
        testResultsFiles: '$(Agent.TempDirectory)/TestResults/results.xml'
      condition: succeededOrFailed()

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: false
        projects: 'src/StableApi/**/*.csproj'
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop
